# Generated by Django 5.2.17 on 2026-08-09 03:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tin', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='TIN')),
                ('identity_card_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Número de carnet de identidad')),
                ('identity_card_complement', models.CharField(blank=True, max_length=10, verbose_name='Complemento del CI')),
                ('identity_card_issued_in', models.CharField(blank=True, max_length=30, verbose_name='Lugar de expedición del CI')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('paternal_last_name', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('maternal_last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de egreso')),
                ('cossmil_card_number', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Número de carnet COSSMIL')),
                ('cossmil_expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento COSSMIL')),
                ('has_driver_license', models.BooleanField(default=False, verbose_name='Tiene licencia de conducir')),
                ('driver_license_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Número de licencia de conducir')),
                ('driver_license_category', models.CharField(blank=True, max_length=20, verbose_name='Categoría de licencia')),
                ('driver_license_expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento de licencia')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Personal activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='organization.position', verbose_name='Cargo')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='organization.rank', verbose_name='Grado')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='organization.section', verbose_name='Sección')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='organization.unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Personal militar',
                'verbose_name_plural': 'Personal militar',
                'ordering': ['paternal_last_name', 'maternal_last_name', 'first_name'],
                'indexes': [models.Index(fields=['unit', 'is_active'], name='personnel_unit_active_idx'), models.Index(fields=['rank', 'is_active'], name='personnel_rank_active_idx')],
            },
        ),
    ]
