# Generated by Django 5.2.17 on 2026-08-09 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='organization.position', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='organization.rank', verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='organization.unit', verbose_name='Unidad'),
        ),
    ]
