# Generated by Django 5.2.17 on 2026-08-12 01:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_serializedmaterial_status'),
        ('organization', '0001_initial'),
        ('personnel', '0002_alter_personnel_position_alter_personnel_rank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerializedMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('OUT', 'Salida'), ('RETURN', 'Retorno')], db_index=True, max_length=20, verbose_name='Tipo de movimiento')),
                ('movement_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('reason', models.CharField(max_length=250, verbose_name='Motivo')),
                ('reference_document', models.CharField(blank=True, max_length=150, verbose_name='Documento de respaldo')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('armory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_material_movements', to='inventory.armory', verbose_name='Armería o depósito')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('responsible_personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_movements_responsible', to='personnel.personnel', verbose_name='Personal responsable')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_material_movements', to='organization.unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Movimiento de material serializado',
                'verbose_name_plural': 'Movimientos de materiales serializados',
                'ordering': ['-movement_at'],
            },
        ),
        migrations.CreateModel(
            name='SerializedMovementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observations', models.CharField(blank=True, max_length=250, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_movement_items', to='inventory.serializedmaterial', verbose_name='Material serializado')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='movements.serializedmovement', verbose_name='Movimiento')),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='movements.serializedmovementitem', verbose_name='Registro de salida original')),
            ],
            options={
                'verbose_name': 'Material de movimiento serializado',
                'verbose_name_plural': 'Materiales de movimientos serializados',
                'ordering': ['material__institutional_code'],
            },
        ),
        migrations.AddIndex(
            model_name='serializedmovement',
            index=models.Index(fields=['unit', 'movement_type'], name='sermov_unit_type_idx'),
        ),
        migrations.AddIndex(
            model_name='serializedmovement',
            index=models.Index(fields=['responsible_personnel', 'movement_at'], name='sermov_person_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='serializedmovementitem',
            constraint=models.UniqueConstraint(fields=('movement', 'material'), name='unique_material_per_sermovement'),
        ),
        migrations.AddConstraint(
            model_name='serializedmovementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source_item__isnull', False)), fields=('source_item',), name='unique_return_per_source_item'),
        ),
    ]
