# Generated by Django 5.2.17 on 2026-08-06 02:41

import apps.accounts.managers
import apps.accounts.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tin', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='TIN')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[apps.accounts.validators.validate_institutional_email], verbose_name='Correo institucional')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('paternal_last_name', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('maternal_last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('role', models.CharField(choices=[('ADMINISTRATOR', 'Administrador'), ('NAVY_COMMAND', 'Comando de la Armada'), ('UNIT_COMMANDER', 'Comandante de Unidad'), ('LOGISTICS_CHIEF', 'Jefe de Cuarta Sección - Logística'), ('ARMAMENT_OFFICER', 'Encargado de Armamento')], max_length=30, verbose_name='Rol')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='Debe cambiar contraseña')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cuenta activa')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso a administración Django')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organization.position', verbose_name='Cargo')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organization.rank', verbose_name='Grado')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organization.section', verbose_name='Sección')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organization.unit', verbose_name='Unidad')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['paternal_last_name', 'maternal_last_name', 'first_name'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
