# Generated by Django 5.2.17 on 2026-08-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cossmil_card_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Número de carnet COSSMIL'),
        ),
        migrations.AddField(
            model_name='user',
            name='cossmil_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento COSSMIL'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license_category',
            field=models.CharField(blank=True, max_length=20, verbose_name='Categoría de licencia'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento de licencia'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Número de licencia de conducir'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_driver_license',
            field=models.BooleanField(default=False, verbose_name='Tiene licencia de conducir'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_card_complement',
            field=models.CharField(blank=True, max_length=10, verbose_name='Complemento del CI'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_card_issued_in',
            field=models.CharField(blank=True, max_length=30, verbose_name='Lugar de expedición del CI'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_card_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Número de carnet de identidad'),
        ),
    ]
