# Generated by Django 5.2.17 on 2026-08-09 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cossmil_card_number_and_more'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personnel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to='personnel.personnel', verbose_name='Personal militar asociado'),
        ),
    ]
