# Generated by Django 5.2.17 on 2026-08-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_migrate_users_to_personnel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='cossmil_card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cossmil_expiration_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_license_category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_license_expiration_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_license_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_driver_license',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity_card_complement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity_card_issued_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity_card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='maternal_last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paternal_last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unit',
        ),
    ]
