# Generated by Django 5.2.17 on 2026-08-06 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caliber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Calibre')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Calibre',
                'verbose_name_plural': 'Calibres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo de componente')),
                ('is_serialized', models.BooleanField(default=False, verbose_name='Tiene identificación individual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de componente',
                'verbose_name_plural': 'Tipos de componentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='País o industria')),
                ('code', models.CharField(blank=True, max_length=5, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'País o industria',
                'verbose_name_plural': 'Países o industrias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Marca o fabricante')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Marca o fabricante',
                'verbose_name_plural': 'Marcas o fabricantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Categoría')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría de material',
                'verbose_name_plural': 'Categorías de material',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Unidad de medida')),
                ('symbol', models.CharField(max_length=15, unique=True, verbose_name='Símbolo')),
                ('allows_decimals', models.BooleanField(default=False, verbose_name='Permite cantidades decimales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Armory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Armería o depósito')),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción o ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armories', to='organization.unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Armería o depósito',
                'verbose_name_plural': 'Armerías o depósitos',
                'ordering': ['unit__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Tipo de material')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('control_method', models.CharField(choices=[('SERIALIZED', 'Control individual o serializado'), ('QUANTITY', 'Control por cantidad o lote')], max_length=20, verbose_name='Método de control')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_types', to='inventory.materialcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Tipo de material',
                'verbose_name_plural': 'Tipos de material',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSpecification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Modelo o especificación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción técnica')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('caliber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_specifications', to='inventory.caliber', verbose_name='Calibre')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_specifications', to='inventory.country', verbose_name='País o industria')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_specifications', to='inventory.manufacturer', verbose_name='Marca o fabricante')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='inventory.materialtype', verbose_name='Tipo de material')),
            ],
            options={
                'verbose_name': 'Modelo o especificación',
                'verbose_name_plural': 'Modelos o especificaciones',
                'ordering': ['material_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SerializedMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institutional_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código institucional')),
                ('identification_number', models.CharField(db_index=True, max_length=100, verbose_name='Número de serie o identificación')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('ASSIGNED', 'Asignado'), ('MAINTENANCE', 'En mantenimiento'), ('OBSERVED', 'Observado'), ('TRANSFER', 'En transferencia'), ('MISSING', 'Extraviado'), ('DISCHARGED', 'Dado de baja')], db_index=True, default='AVAILABLE', max_length=30, verbose_name='Estado administrativo')),
                ('physical_condition', models.CharField(choices=[('GOOD', 'Bueno'), ('REGULAR', 'Regular'), ('DAMAGED', 'Dañado'), ('UNVERIFIED', 'No verificado')], default='UNVERIFIED', max_length=30, verbose_name='Estado físico')),
                ('manufacturing_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de fabricación')),
                ('acquisition_source', models.CharField(blank=True, max_length=150, verbose_name='Procedencia o forma de adquisición')),
                ('registration_document', models.CharField(blank=True, max_length=150, verbose_name='Documento de alta o registro')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Registro activo')),
                ('armory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_materials', to='inventory.armory', verbose_name='Armería o depósito actual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_serialized_materials', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_materials', to='inventory.materialspecification', verbose_name='Modelo o especificación')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_materials', to='organization.unit', verbose_name='Unidad responsable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_serialized_materials', to=settings.AUTH_USER_MODEL, verbose_name='Última modificación por')),
            ],
            options={
                'verbose_name': 'Material individual o serializado',
                'verbose_name_plural': 'Materiales individuales o serializados',
                'ordering': ['institutional_code'],
            },
        ),
        migrations.CreateModel(
            name='SerializedMaterialComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identification_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de identificación')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_components', to='inventory.componenttype', verbose_name='Tipo de componente')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.serializedmaterial', verbose_name='Material principal')),
            ],
            options={
                'verbose_name': 'Componente de material',
                'verbose_name_plural': 'Componentes de material',
                'ordering': ['material__institutional_code', 'component_type__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código interno')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Existencia mínima')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_materials', to='inventory.materialspecification', verbose_name='Modelo o especificación')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_materials', to='inventory.unitofmeasure', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Material controlado por cantidad',
                'verbose_name_plural': 'Materiales controlados por cantidad',
                'ordering': ['internal_code'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Número de lote')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Cantidad inicial')),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Cantidad actual')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fabricación')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OBSERVED', 'Observado'), ('EXPIRED', 'Vencido'), ('DEPLETED', 'Agotado'), ('DISCHARGED', 'Dado de baja')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='Estado')),
                ('physical_condition', models.CharField(choices=[('GOOD', 'Bueno'), ('REGULAR', 'Regular'), ('DAMAGED', 'Dañado'), ('UNVERIFIED', 'No verificado')], default='UNVERIFIED', max_length=30, verbose_name='Estado físico')),
                ('acquisition_source', models.CharField(blank=True, max_length=150, verbose_name='Procedencia o forma de adquisición')),
                ('registration_document', models.CharField(blank=True, max_length=150, verbose_name='Documento de alta o registro')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Registro activo')),
                ('armory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='inventory.armory', verbose_name='Armería o depósito actual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_batches', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='organization.unit', verbose_name='Unidad responsable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_stock_batches', to=settings.AUTH_USER_MODEL, verbose_name='Última modificación por')),
                ('stock_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.stockmaterial', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Lote o existencia',
                'verbose_name_plural': 'Lotes o existencias',
                'ordering': ['stock_material__internal_code', 'lot_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='armory',
            constraint=models.UniqueConstraint(fields=('unit', 'code'), name='unique_armory_code_unit'),
        ),
        migrations.AddConstraint(
            model_name='armory',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_armory_name_unit'),
        ),
        migrations.AddConstraint(
            model_name='materialtype',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_type_name_category'),
        ),
        migrations.AddConstraint(
            model_name='materialspecification',
            constraint=models.UniqueConstraint(fields=('material_type', 'name'), name='unique_material_spec'),
        ),
        migrations.AddIndex(
            model_name='serializedmaterial',
            index=models.Index(fields=['unit', 'status'], name='serialized_unit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serializedmaterial',
            index=models.Index(fields=['armory', 'status'], name='serial_armory_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='serializedmaterial',
            constraint=models.UniqueConstraint(fields=('specification', 'identification_number'), name='unique_serial_per_spec'),
        ),
        migrations.AddConstraint(
            model_name='serializedmaterialcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='component_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='serializedmaterialcomponent',
            constraint=models.UniqueConstraint(fields=('component_type', 'identification_number'), name='unique_component_ident'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['unit', 'status'], name='stockbatch_unit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['armory', 'status'], name='stock_armory_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('initial_quantity__gt', 0)), name='batch_initial_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0)), name='batch_current_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('current_quantity__lte', models.F('initial_quantity'))), name='batch_current_not_above_initial'),
        ),
        migrations.AddConstraint(
            model_name='stockmaterial',
            constraint=models.UniqueConstraint(fields=('specification', 'unit_of_measure'), name='unique_stock_spec_unit'),
        ),
        migrations.AddConstraint(
            model_name='stockmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stock__gte', 0)), name='stock_minimum_nonnegative'),
        ),
    ]
