# Generated by Django 5.2.17 on 2026-08-11 00:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('OUT', 'Salida'), ('RETURN', 'Devolución / Reintegro'), ('ADJUSTMENT_IN', 'Ajuste positivo'), ('ADJUSTMENT_OUT', 'Ajuste negativo')], db_index=True, max_length=30, verbose_name='Tipo de movimiento')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Cantidad')),
                ('previous_quantity', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14, verbose_name='Cantidad anterior')),
                ('new_quantity', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14, verbose_name='Cantidad posterior')),
                ('reason', models.CharField(max_length=250, verbose_name='Motivo')),
                ('reference_document', models.CharField(blank=True, max_length=150, verbose_name='Documento de respaldo')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('armory', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.armory', verbose_name='Armería o depósito')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockbatch', verbose_name='Lote')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('unit', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organization.unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Movimiento de existencia',
                'verbose_name_plural': 'Movimientos de existencias',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_positive'), models.CheckConstraint(condition=models.Q(('previous_quantity__gte', 0)), name='stock_movement_previous_nonnegative'), models.CheckConstraint(condition=models.Q(('new_quantity__gte', 0)), name='stock_movement_new_nonnegative')],
            },
        ),
    ]
