# Generated by Django 5.2.17 on 2026-08-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializedmaterial',
            name='allocation_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Dotación individual'), ('UNIT', 'Dotación de unidad')], db_index=True, default='UNIT', max_length=20, verbose_name='Tipo de dotación'),
        ),
    ]
