# Generated by Django 5.2.17 on 2026-08-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_serializedmaterial_allocation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializedmaterial',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('ASSIGNED', 'Asignado'), ('ISSUED', 'Salida temporal'), ('MAINTENANCE', 'En mantenimiento'), ('OBSERVED', 'Observado'), ('TRANSFER', 'En transferencia'), ('MISSING', 'Extraviado'), ('DISCHARGED', 'Dado de baja')], db_index=True, default='AVAILABLE', max_length=30, verbose_name='Estado administrativo'),
        ),
    ]
