# Generated by Django 5.2.17 on 2026-08-09 06:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora de dotación')),
                ('assignment_document', models.CharField(blank=True, max_length=150, verbose_name='Documento de respaldo de entrega')),
                ('assignment_observations', models.TextField(blank=True, verbose_name='Observaciones de entrega')),
                ('status', models.CharField(choices=[('ACTIVE', 'Dotación activa'), ('RETURNED', 'Devuelto')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado de la dotación')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de devolución')),
                ('return_document', models.CharField(blank=True, max_length=150, verbose_name='Documento de respaldo de devolución')),
                ('return_observations', models.TextField(blank=True, verbose_name='Observaciones de devolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_assignments', to='inventory.serializedmaterial', verbose_name='Material serializado')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_assignments', to='personnel.personnel', verbose_name='Personal militar')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_assignments_returned', to=settings.AUTH_USER_MODEL, verbose_name='Devolución registrada por')),
            ],
            options={
                'verbose_name': 'Dotación individual',
                'verbose_name_plural': 'Dotaciones individuales',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualAssignmentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_delivered', models.PositiveIntegerField(default=1, verbose_name='Cantidad entregada')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_components', to='assignments.individualassignment', verbose_name='Dotación individual')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_records', to='inventory.serializedmaterialcomponent', verbose_name='Componente entregado')),
            ],
            options={
                'verbose_name': 'Componente de dotación individual',
                'verbose_name_plural': 'Componentes de dotaciones individuales',
                'ordering': ['component__component_type__name'],
            },
        ),
        migrations.AddIndex(
            model_name='individualassignment',
            index=models.Index(fields=['personnel', 'status'], name='assign_person_status_idx'),
        ),
        migrations.AddIndex(
            model_name='individualassignment',
            index=models.Index(fields=['material', 'status'], name='assign_material_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='individualassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('material',), name='unique_active_assignment_material'),
        ),
        migrations.AddConstraint(
            model_name='individualassignmentcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delivered__gte', 1)), name='assignment_component_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='individualassignmentcomponent',
            constraint=models.UniqueConstraint(fields=('assignment', 'component'), name='unique_component_per_assignment'),
        ),
    ]
