# Generated by Django 5.2.17 on 2026-08-11 01:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('inventory', '0002_stockmovement'),
        ('personnel', '0002_alter_personnel_position_alter_personnel_rank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualAssignmentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moment', models.CharField(choices=[('DELIVERY', 'Entrega'), ('RETURN', 'Devolución')], max_length=20, verbose_name='Momento de la fotografía')),
                ('photo_type', models.CharField(choices=[('GENERAL', 'Vista general'), ('SERIAL', 'Número de identificación o serie'), ('LEFT_SIDE', 'Lado izquierdo'), ('RIGHT_SIDE', 'Lado derecho'), ('COMPONENTS', 'Componentes'), ('OTHER', 'Otra fotografía')], default='GENERAL', max_length=20, verbose_name='Tipo de fotografía')),
                ('photo', models.ImageField(upload_to='assignments/photos/%Y/%m/', verbose_name='Fotografía')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Fotografía de dotación individual',
                'verbose_name_plural': 'Fotografías de dotaciones individuales',
                'ordering': ['moment', 'photo_type', 'created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='individualassignment',
            name='unique_active_assignment_material',
        ),
        migrations.AddConstraint(
            model_name='individualassignment',
            constraint=models.UniqueConstraint(fields=('material',), name='unique_assignment_material_lifetime'),
        ),
        migrations.AddField(
            model_name='individualassignmentphoto',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='assignments.individualassignment', verbose_name='Dotación individual'),
        ),
        migrations.AddField(
            model_name='individualassignmentphoto',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_assignment_photos_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddIndex(
            model_name='individualassignmentphoto',
            index=models.Index(fields=['assignment', 'moment'], name='assign_photo_moment_idx'),
        ),
    ]
