# Generated by Django 5.2.17 on 2026-08-13 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_individualassignmentphoto_and_more'),
        ('inventory', '0004_alter_serializedmaterial_status'),
        ('personnel', '0002_alter_personnel_position_alter_personnel_rank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='individualassignment',
            name='unique_assignment_material_lifetime',
        ),
        migrations.AddConstraint(
            model_name='individualassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('material',), name='unique_active_assignment_material'),
        ),
    ]
