# Generated by Django 5.2.17 on 2026-08-13 01:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_remove_individualassignment_unique_assignment_material_lifetime_and_more'),
        ('inventory', '0004_alter_serializedmaterial_status'),
        ('organization', '0001_initial'),
        ('personnel', '0002_alter_personnel_position_alter_personnel_rank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualassignment',
            name='assignment_document',
            field=models.CharField(blank=True, max_length=150, verbose_name='Documento de respaldo de dotación'),
        ),
        migrations.AlterField(
            model_name='individualassignment',
            name='assignment_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones de dotación'),
        ),
        migrations.AlterField(
            model_name='individualassignment',
            name='return_document',
            field=models.CharField(blank=True, max_length=150, verbose_name='Documento de cierre de dotación'),
        ),
        migrations.AlterField(
            model_name='individualassignment',
            name='return_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones de cierre'),
        ),
        migrations.AlterField(
            model_name='individualassignment',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de cierre'),
        ),
        migrations.AlterField(
            model_name='individualassignment',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_assignments_returned', to=settings.AUTH_USER_MODEL, verbose_name='Cierre registrado por'),
        ),
        migrations.AlterField(
            model_name='individualassignment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Dotación activa'), ('RETURNED', 'Dotación finalizada')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado de la dotación'),
        ),
        migrations.AlterField(
            model_name='individualassignmentphoto',
            name='moment',
            field=models.CharField(choices=[('DELIVERY', 'Entrega'), ('RETURN', 'Devolución definitiva')], max_length=20, verbose_name='Momento de la fotografía'),
        ),
        migrations.CreateModel(
            name='IndividualAssignmentCustodyMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('DELIVERY', 'Entrega al personal'), ('RECEIPT', 'Recepción en pañol')], db_index=True, max_length=20, verbose_name='Tipo de movimiento')),
                ('movement_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('reason', models.CharField(max_length=250, verbose_name='Motivo')),
                ('reference_document', models.CharField(blank=True, max_length=150, verbose_name='Documento de respaldo')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_custody_movements', to='inventory.armory', verbose_name='Armería / Pañol')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_custody_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_custody_movements', to='personnel.personnel', verbose_name='Personal militar')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_custody_movements', to='organization.unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Movimiento de custodia de dotación individual',
                'verbose_name_plural': 'Movimientos de custodia de dotaciones individuales',
                'ordering': ['-movement_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualAssignmentCustodyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_items', to='assignments.individualassignment', verbose_name='Dotación individual')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assignments.individualassignmentcustodymovement', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Material de movimiento de custodia',
                'verbose_name_plural': 'Materiales de movimientos de custodia',
            },
        ),
        migrations.AddIndex(
            model_name='individualassignmentcustodymovement',
            index=models.Index(fields=['personnel', 'movement_type'], name='assign_cust_person_type_idx'),
        ),
        migrations.AddIndex(
            model_name='individualassignmentcustodymovement',
            index=models.Index(fields=['unit', 'movement_at'], name='assign_cust_unit_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='individualassignmentcustodyitem',
            constraint=models.UniqueConstraint(fields=('movement', 'assignment'), name='unique_assignment_per_custody_movement'),
        ),
    ]
