# Generated by Django 5.2.17 on 2026-08-06 02:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Acción')),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Correcto'), ('FAILED', 'Fallido')], default='SUCCESS', max_length=20, verbose_name='Resultado')),
                ('target_model', models.CharField(blank=True, max_length=150, verbose_name='Modelo afectado')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='ID afectado')),
                ('target_repr', models.CharField(blank=True, max_length=255, verbose_name='Registro afectado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador o dispositivo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='organization.unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['unit', 'created_at'], name='audit_audit_unit_id_2a1417_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx')],
            },
        ),
    ]
