# Generated by Django 5.2.17 on 2026-08-22 04:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('personnel', '0002_alter_personnel_position_alter_personnel_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualFiliationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('logistics_chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiation_configs_as_logistics_chief', to='personnel.personnel', verbose_name='Jefe de la Sección IV Logística')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='individual_filiation_config', to='organization.unit', verbose_name='Unidad')),
                ('unit_commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiation_configs_as_unit_commander', to='personnel.personnel', verbose_name='Comandante de la unidad')),
                ('verification_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiation_configs_as_verifier', to='personnel.personnel', verbose_name='Responsable de la verificación')),
            ],
            options={
                'verbose_name': 'Configuración de filiación individual',
                'verbose_name_plural': 'Configuraciones de filiación individual',
                'ordering': ['unit__name'],
            },
        ),
    ]
